# Generated by Django 4.2 on 2026-05-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capteurs', '0002_dht11'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('temperature_threshold', models.FloatField(default=26)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
